### ISSUE TITLE
[FEATURE] Able to dual watch while the radio is on.

### ISSUE THREAD

**Issue by troilus** [kamilsss655/uv-k5-firmware-custom#209]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem this feature solves.

It is a known issue that described in wiki "known bugs

dual watch is not working while the radio is on, only primary channel interrupts the radio (this was present in previous implementation as well)"

**Describe the solution you'd like**
Radio able to dual watch while in FM radio.

**Comment by kamilsss655** [comment]
Yup, this is a known issue and related to the way dual watch is implemented in original firmware.

I tried resolving it, but the code base around the dual-watch was way too complicated.

Moreover during my tests of the dual watch switching during FM reception I was getting audible switching sound. This may or may not be due to the implementation I tried, so perhaps someone will resolve this issue one day. I myself do not intend to fix it.
