### ISSUE TITLE
BW (Menu 2) is not stored

### ISSUE THREAD

**Issue by OE1MWW** [kamilsss655/uv-k5-firmware-custom#25]
Changing BW (Menu 2) to another value (for example from 25k to 12.5k) and cycle Power off/on, it will be - as in the example - 25K again.

**Comment by ErikS-web** [comment]
Indeed, When power off/on it's back to 25.

Also when switching from VFO to a Memory Channel

**Comment by OE1MWW** [comment]
unfortunately does this bug still exist in 0.16.2

**Comment by kamilsss655** [comment]
It is not a bug.

If you want the changes made to the memory channel saved, you need to save them with menu 17 `ChSave` function.

NOTE: New filter BWs `8.33k, 6.25k, 5k` will not be saved due to CHIRP EEPROM convention that allows to store channel BW with only 1 bit, allowing to store only 2 possible BW values. In the future, once this convention changes or I modify the CHIRP driver we can store new BWs as well.

**Comment by sparky93a** [comment]
ahh this relates to  my issue logged today. will see if i can close/delete #32
