### ISSUE TITLE
[BUG] FM Radio frozen

### ISSUE THREAD

**Issue by LordVertice** [kamilsss655/uv-k5-firmware-custom#81]
**Describe the bug**
When I try to change the frequency (or do pretty much anything) in the FM Radio, it freezes the entire radio completely. Rebooting appears to be the only fix.

**To Reproduce**
1. Open the FM Radio
2. Press UP or DOWN
3. Try to exit

**Expected behavior**
The FM Radio should work, and I should be able to adjust the frequency.

**Pictures/video**
![photo_2024-01-18_20-17-49](https://github.com/kamilsss655/uv-k5-firmware-custom/assets/56739341/d628529b-2b65-47e5-8c21-7eba69dbaa83)
(it's just stuck there. looks incomplete?)

**Details:**
- Firmware version: v.19.6 (also tested with v.19.5)
- Bandwidth: any
- Power: any
- RxAGC: any
- Gain settings (LNAs/LNA/PGA): default, probably
- other: Pretty sure it worked when I built from a random commit around v.19.4 or so, but of course I didn't note which one it was or what I changed in the Makefile. Sorry about that.

**Comment by kamilsss655** [comment]
Good bug report!

It is issue with loading the last played frequency from EEPROM that lacks validation. For now you might want to try pressing DOWN and being patient and maybe the fm chip will tune down to valid frequency, otherwise the EEPROM value needs to be changed to valid value.

This needs a FW fix though.
